### ISSUE TITLE
Input field bug

### ISSUE THREAD

**Issue by Dahyeeee** [ReactMiniProject-team1/News-Search-App#54]
input 창에 검색어 입력하고 enter를 치면 화면이 새로고침되고 검색기능도 없어져요.

- [x] enter 기능 구현할지 정하기
- [x] 버그 없애기

**Comment by Yupmac** [comment]
입력창 감싸는 태그를 div ---> form 변경하고나서 발생했습니다.
form 기본 동작으로 인한 현상인데 제가 실수로 preventDefault() 빼먹었네요.
 
수정해서 재업할게요.

**Comment by Yupmac** [comment]
> input 창에 검색어 입력하고 enter를 치면 화면이 새로고침되고 검색기능도 없어져요.
> 
> * [x]  버그 없애기

수정 완료!
PR했어요.

---
> * [x]  enter 기능 구현할지 정하기

저는 굳이 필요 없을거 같다고 생각해요.
검색어 입력하고 0.5초만에 결과 출력되다보니 enter 키는 별 의미 없는거 같아요.
enter 키 기능을 넣을 거라면 0.5초 후 자동 검색되는 기능을 꺼야 될거 같아요.

**Comment by Dahyeeee** [comment]
네 확인하고 수정해주셔서 감사해요 ~~^ㅇ^
